# -*- coding: utf-8 -*-
"""Project_Insurence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RGT-TYvyH6j-4_p0eXwQj7sYXID95fE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv()

"""**🔹 1. Label Encoding kya hota hai?

👉 Categories ko numbers me convert karna**

Example:
Color = ["Red", "Green", "Blue"]

Label Encoding ke baad:

Red   → 0  
Green → 1  
Blue  → 2

**🔥 2. One Hot Encoding kya hota hai?

👉 Har category ko separate column me convert karta hai**

*Example:
Color = ["Red", "Green", "Blue"]

One Hot Encoding:

Red    → [1, 0, 0]
Green  → [0, 1, 0]
Blue   → [0, 0, 1]*

**Feature Scaling**

👉 Jab dataset me different columns ke values alag-alag scale pe hote hain, tab unhe same range me lana = Feature Scaling

Example:
Age = 20, 30, 40  
Salary = 20000, 50000, 100000

👉 Problem:

Salary ka range bahut bada hai
Model salary ko zyada importance dega ❌

👉 Solution:
Scaling ✔️

**Normalization**

👉 Data ko 0 se 1 ke beech le aata hai

📌 Formula:
X_new = (X - X_min) / (X_max - X_min)
🔍 Example:
Value = 20, 30, 40  
Normalized = 0, 0.5, 1

**Standardization**

👉 Data ko mean = 0, std = 1 pe convert karta hai

📌 Formula:
X_new = (X - mean) / standard deviation
🔍 Example:
Mean = 30  
Values → -1, 0, +1 type me convert ho jate hain

**EDA**
"""

df=pd.read_csv('/content/insurance.csv')
df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.columns

numeric_columns=['age', 'bmi', 'children', 'charges']
for col in numeric_columns:
  plt.figure(figsize=(6,4))
  sns.distplot(df[col])

sns.countplot(x=df['children'])

sns.countplot(x=df['smoker'])

sns.countplot(x=df['sex'])

for col in numeric_columns:
  plt.figure(figsize=(6,4))
  sns.boxplot(x=df[col])

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True)

"""**Preprocessing**"""

df_cleaned=df.copy()
df_cleaned.shape

df_cleaned.drop_duplicates(inplace=True)
df_cleaned.shape

df_cleaned.isnull().sum()

df_cleaned.dtypes

df_cleaned['sex'].value_counts()

"""**Label Encoding on df**"""

df_cleaned['sex'] = df_cleaned['sex'].str.lower().str.strip()

df_cleaned['sex'] = df_cleaned['sex'].map({
    "male": 0,
    "female": 1
})

df_cleaned

df_cleaned['smoker'].value_counts()

df_cleaned['smoker'] = df_cleaned['smoker'].str.lower().str.strip()

df_cleaned['smoker'] = df_cleaned['smoker'].map({
    "yes": 1,
    "no": 0
})

df_cleaned

df_cleaned.rename(columns={
    'sex':'is_female',
    'smoker':'is_smoker'
},inplace=True)

df_cleaned

df['region'].value_counts()

"""**one hot encoding**"""

df_cleaned = pd.get_dummies(df_cleaned, columns=['region'], drop_first=True)

df_cleaned

df

df_cleaned=df_cleaned.astype(int)
df_cleaned

"""**Feature Engineering and Extraction**"""

sns.displot(df_cleaned['bmi'])

df_cleaned['bmi_category']=pd.cut(
    df_cleaned['bmi'],
    bins=[0,18.5,24.9,29.9,float('inf')],
    labels=['underweight','normal','overweight','obese']

)

df_cleaned

df_cleaned = pd.get_dummies(df_cleaned, columns=['bmi_category'], drop_first=True)

df_cleaned

df_cleaned=df_cleaned.astype(int)

df_cleaned

"""**Scaling**"""

df_cleaned.columns

from sklearn.preprocessing import StandardScaler
cols=['age','bmi','children']
scaler=StandardScaler()
df_cleaned[cols]=scaler.fit_transform(df_cleaned[cols])

df_cleaned

# ------------------------------
# Pearson Correlation with Target
# ------------------------------

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# List of features to check against target
selected_features = [
    'age', 'bmi', 'children', 'is_female', 'is_smoker',
    'region_northwest', 'region_southeast', 'region_southwest',
    'bmi_category_normal', 'bmi_category_overweight', 'bmi_category_obese'
]

# Calculate Pearson correlation for each feature
correlations = {
    feature: pearsonr(df_cleaned[feature], df_cleaned['charges'])[0]
    for feature in selected_features
    if feature in df_cleaned.columns  # safe check in case some column is missing
}

# Convert dictionary to DataFrame
corr_df = pd.DataFrame(list(correlations.items()), columns=['feature', 'pearson_correlation'])

# Sort by absolute correlation (strongest first)
corr_df['abs_correlation'] = corr_df['pearson_correlation'].abs()
corr_df = corr_df.sort_values(by='abs_correlation', ascending=False).drop('abs_correlation', axis=1)

# Display correlation table
print(corr_df)

# ------------------------------
# Heatmap Visualization
# ------------------------------
plt.figure(figsize=(10,6))
sns.heatmap(corr_df.set_index('feature'), annot=True, cmap='coolwarm', center=0)
plt.title("Pearson Correlation of Features with Charges")
plt.show()

# ------------------------------
# Chi-Square Test for Categorical Features
# ------------------------------

import pandas as pd
from scipy.stats import chi2_contingency

# Categorical features to test
cat_features = [
    'is_female', 'is_smoker',
    'region_northwest', 'region_southeast', 'region_southwest',
    'bmi_category_normal', 'bmi_category_overweight', 'bmi_category_obese'
]

# Significance level
alpha = 0.05

# Bin the target variable into 4 quartiles
df_cleaned['charges_bin'] = pd.qcut(df_cleaned['charges'], q=4, labels=False)

# Dictionary to store results
chi2_results = {}

for col in cat_features:
    if col in df_cleaned.columns:
        # Contingency table
        contingency = pd.crosstab(df_cleaned[col], df_cleaned['charges_bin'])

        # Chi-square test
        chi2_stat, p_val, _, _ = chi2_contingency(contingency)

        # Decision
        decision = 'Reject Null (Keep Feature)' if p_val < alpha else 'Accept Null (Drop Feature)'

        # Store results
        chi2_results[col] = {
            'chi2_statistic': chi2_stat,
            'p_value': p_val,
            'Decision': decision
        }
    else:
        print(f"Warning: Column {col} not found in dataframe")

# Convert results to DataFrame for easy viewing
chi2_df = pd.DataFrame(chi2_results).T  # Transpose for better format
chi2_df = chi2_df.sort_values(by='chi2_statistic', ascending=False)

# Display results
print(chi2_df)

final_df=df_cleaned[['age','is_female','bmi','children','is_smoker','charges','region_southeast','bmi_category_obese',]]

final_df

# ------------------------------
# 1. Imports
# ------------------------------

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# ------------------------------
# 2. Prepare Features and Target
# ------------------------------
# Features (X) and target (y)
X = df_cleaned[['age','is_female','bmi','children','is_smoker','region_southeast','bmi_category_obese']]
y = df_cleaned['charges']

# ------------------------------
# 3. Train-Test Split
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ------------------------------
# 4. Train Linear Regression
# ------------------------------
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Predict on test set
y_pred_lr = lr_model.predict(X_test)

# Evaluate
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Performance:")
print("MSE:", mse_lr)
print("R2 Score:", r2_lr)

# ------------------------------
# 5. Optional: Random Forest Regression
# ------------------------------
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("\nRandom Forest Regression Performance:")
print("MSE:", mse_rf)
print("R2 Score:", r2_rf)

# ------------------------------
# 6. Predicting for new input
# ------------------------------
# Example: new data row
import numpy as np

new_input = pd.DataFrame([{
    'age': 0.5,
    'is_female': 1,
    'bmi': 0.2,
    'children': 0,
    'is_smoker': 0,
    'region_southeast': 1,
    'bmi_category_obese': 0
}])

predicted_charge = rf_model.predict(new_input)
print("\nPredicted charges for new input:", predicted_charge[0])